FROM ubuntu:18.04
LABEL version=1.0.0
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    curl \
    sudo 

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - \
    && sudo apt-get install -y nodejs


COPY . .

WORKDIR /usr/src/app/app/frontend/wellness

RUN npm install \
    npm install --global expo-cli \
    npm install react-native \
    npm install expo \
    npm install metro-bundler \
    npm install react-native-screens@3.4.0

EXPOSE 19000
EXPOSE 19001
EXPOSE 19002
EXPOSE 19006

CMD npm expo start





