FROM node:14.0.0
LABEL version=1.0.0

WORKDIR /usr/src/app/

COPY . .

WORKDIR /usr/src/app/app/frontend/wellness/

RUN apt-get update \
    && apt-get install -y \
    curl \
    sudo

# ENV REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
# ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

RUN curl --compressed -o- -L https://yarnpkg.com/install.sh | bash

# RUN npm install
# RUN yarn global add expo-cli 
# RUN yarn global add metro-bundler  
# RUN yarn global add react-native-screens

RUN sudo yarn install 

RUN npm install 
RUN npm install -g npm
RUN npm install --global expo-cli@3.28.6 
RUN npm install --global expo 
RUN npm install --global react-native 
RUN npm install --global react-native screens@3.4.0
RUN npm install --global metro-bundler 

# RUN sudo yarn global add expo-cli@3.28.6
# RUN sudo yarn add metro-bundler 

# RUN sudo npm cache clean --force && sudo yarn cache clean

EXPOSE 19000
EXPOSE 19001
EXPOSE 19002
EXPOSE 19006

# RUN cd /usr/src/app/app/frontend/wellness/

# ENTRYPOINT ["expo"]
CMD npm start

